require("dotenv").config();
const express=require("express"); const cors=require("cors"); const path=require("path");
const ligneRoutes=require("./routes/ligneRoutes"); const arretRoutes=require("./routes/arretRoutes"); const authRoutes=require("./routes/authRoutes"); const userRoutes=require("./routes/userRoutes"); const favoriRoutes=require("./routes/favoriRoutes"); const rechercheRoutes=require("./routes/rechercheRoutes"); const statsRoutes=require("./routes/statsRoutes"); const parametreRoutes=require("./routes/parametreRoutes");
const {adminPageGuard}=require("./middlewares/auth");
const app=express(); const frontend=path.join(__dirname,"..","frontend");
app.use(cors({origin:true,credentials:true})); app.use(express.json({limit:"7mb"})); app.use(express.urlencoded({extended:true}));
app.use("/uploads",express.static(path.join(__dirname,"uploads")));
app.use("/auth",express.static(path.join(frontend,"auth")));
app.use("/admin",(req,res,next)=>{if(req.path==="/login.html"||req.path==="/login.html/")return next();
    return adminPageGuard(req,res,next);},express.static(path.join(frontend,"admin")));
app.use(express.static(frontend));
app.use("/api/auth",authRoutes); 
app.use("/api/utilisateurs",userRoutes);
 app.use("/api/favoris",favoriRoutes);
  app.use("/api/recherches",rechercheRoutes); 
 app.use("/api/stats",statsRoutes); app.use("/api/parametres",parametreRoutes); 
 app.use("/api/lignes",ligneRoutes); 
 app.use("/api/arrets",arretRoutes);
app.get("/",(req,res)=>res.sendFile(path.join(frontend,"index.html")));
app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({message:err.message||"Erreur serveur"});});
module.exports=app;
