const express=require("express");
const router=express.Router(); 
const C=require("../controllers/ligneController");
const {requireAdmin}=require("../middlewares/auth");
router.get("/",C.getAll);
router.get("/trajet",C.rechercherTrajet);
router.get("/correspondance",C.rechercherCorrespondance); 
router.get("/:id",C.getById); 
router.post("/",requireAdmin,C.create); 
router.put("/:id",requireAdmin,C.update);
router.delete("/:id",requireAdmin,C.delete); 
module.exports=router;
